services:
  build:
    image: adoyle/quartz-deploy:latest
    container_name: quartz-build
    init: true
    command: "npx quartz build --verbose"
    build:
      context: $CONTENT_DIR
      dockerfile: $QUART_DEPLOY_DIR/Dockerfile
      args:
        GITHUB_PROXY: $GITHUB_PROXY
        APT_MIRROR: $APT_MIRROR
    volumes:
      - $CONTENT_DIR/.public:/root/quartz/public
      - $CONTENT_DIR:/root/quartz/content
      - $QUARTZ_CONFIG:/root/quartz/quartz.config.ts
      - $QUARTZ_LAYOUT:/root/quartz/quartz.layout.ts
      - $QUART_DEPLOY_DIR/quartz/styles/custom.scss:/root/quartz/quartz/styles/custom.scss
      - $QUART_DEPLOY_DIR/quartz/static/icon.png:/root/quartz/quartz/static/icon.png
      # Componentss
      - $QUART_DEPLOY_DIR/quartz/components/pages/FolderContent.tsx:/root/quartz/components/pages/FolderContent.tsx
      - $QUART_DEPLOY_DIR/quartz/components/Date.tsx:/root/quartz/quartz/components/Date.tsx
      - $QUART_DEPLOY_DIR/quartz/components/Footer.tsx:/root/quartz/quartz/components/Footer.tsx
      - $QUART_DEPLOY_DIR/quartz/components/Head.tsx:/root/quartz/quartz/components/Head.tsx
      # Plugins
      - $QUART_DEPLOY_DIR/quartz/plugins/transformers/index.ts:/root/quartz/quartz/plugins/transformers/index.ts
      - $QUART_DEPLOY_DIR/quartz/plugins/transformers/improved-image.ts:/root/quartz/quartz/plugins/transformers/improved-image.ts
      - $QUART_DEPLOY_DIR/quartz/plugins/emitters/contentIndex.tsx:/root/quartz/quartz/plugins/emitters/contentIndex.tsx
    post_start:
      - command: rm -rf /root/quartz/public/*

  serve:
    image: adoyle/quartz-deploy:latest
    container_name: quartz-serve
    restart: unless-stopped
    init: true
    build:
      context: $CONTENT_DIR
      dockerfile: $QUART_DEPLOY_DIR/Dockerfile
      args:
        GITHUB_PROXY: $GITHUB_PROXY
        APT_MIRROR: $APT_MIRROR
    command: "npx quartz build --verbose --serve"
    volumes:
      - $CONTENT_DIR:/root/quartz/content
      - $QUARTZ_CONFIG:/root/quartz/quartz.config.ts
      - $QUARTZ_LAYOUT:/root/quartz/quartz.layout.ts
      - $QUART_DEPLOY_DIR/quartz/styles/custom.scss:/root/quartz/quartz/styles/custom.scss
      - $QUART_DEPLOY_DIR/quartz/static/icon.png:/root/quartz/quartz/static/icon.png
      # Componentss
      - $QUART_DEPLOY_DIR/quartz/components/pages/FolderContent.tsx:/root/quartz/quartz/components/pages/FolderContent.tsx
      - $QUART_DEPLOY_DIR/quartz/components/Date.tsx:/root/quartz/quartz/components/Date.tsx
      - $QUART_DEPLOY_DIR/quartz/components/Footer.tsx:/root/quartz/quartz/components/Footer.tsx
      - $QUART_DEPLOY_DIR/quartz/components/Head.tsx:/root/quartz/quartz/components/Head.tsx
      # Plugins
      - $QUART_DEPLOY_DIR/quartz/plugins/transformers/index.ts:/root/quartz/quartz/plugins/transformers/index.ts
      - $QUART_DEPLOY_DIR/quartz/plugins/transformers/improved-image.ts:/root/quartz/quartz/plugins/transformers/improved-image.ts
      - $QUART_DEPLOY_DIR/quartz/plugins/emitters/contentIndex.tsx:/root/quartz/quartz/plugins/emitters/contentIndex.tsx
    ports:
      - ${PORT:-8080}:8080
